arb-dir: lib/localization/arb
template-arb-file: app_pt.arb
output-localization-file: app_localizations.dart
output-dir: lib/localization/generated
nullable-getter: false

# Needed to ensure the formatter does not run on the generated files.
# See https://github.com/dart-lang/dart_style/issues/864 for more information
header: "// dart format off\n// coverage:ignore-file"